version: '2.3'
services:

  dev_db:
    image: mongo:5.0
    volumes:
      - './docker/mongo/000-init.js:/docker-entrypoint-initdb.d/000-init.js:ro'
      - 'dev_dbdata:/data/db'
    ports:
      - '27017:27017'
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}

  dev_mongoexpress:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@dev_db:27017/

  dev_app:
    image: wideochmurka:dev_laravel-php8.1-fpm-bullseye
    command: php artisan serve --host=0.0.0.0 --port=8000
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - '.:/usr/local/apache2/htdocs/'
      - './docker/php/php.ini-development:/usr/local/etc/php/php.ini'
    depends_on:
      - dev_db

volumes:
  dev_dbdata:
