version: '2.3'
services:

  dev_db:
    image: mysql:8.0
    volumes:
      - "dev_dbdata:/var/lib/mysql"
    ports:
      - "8306:3306"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  dev_phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - dev_db

  dev_app:
    image: wideochmurka:dev_laravel-php8.1-fpm-bullseye
    command: php artisan serve --host=0.0.0.0 --port=8000
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - '.:/usr/local/apache2/htdocs/'
      - './docker/php/php.ini-development:/usr/local/etc/php/php.ini'
    user: 1000:1000
    depends_on:
      - dev_db

volumes:
  dev_dbdata:
